Inzien semesters gevolgd
RubenJ01/OOSDGroep3 pull request #18
Opened 2023-12-14 12:01 UTC by JoelleDoorn

De query en de code voor het inzien van semester die je gevolgd heb of aan het volgen ben

2023-12-14 12:03 UTC, BurnoBoek commented on SmartUp/SmartUp.DataAccess.SQLServer/Dao/GradeDao.cs
> +
Onnodige enters

2023-12-14 12:08 UTC, BurnoBoek approved these changes
Alleen ff de enters weghalen dan is het goed, ziet er voor de rest goed uit

2023-12-14 13:20 UTC, RubenJ01 commented on SmartUp/SmartUp.DataAccess.SQLServer/Dao/GradeDao.cs
> +
Man brand los

2023-12-14 13:23 UTC, RubenJ01 requested changes

2023-12-14 13:23 UTC, RubenJ01 commented on SmartUp/SmartUp.DataAccess.SQLServer/Dao/SemesterDao.cs
> +        public List<Semester> GetAllSemestersWithRegistration(string studentId)
Sorry ik ga heel moeilijk doen, in de nieuwe code willen we geen connecties meer openen binnen in de dao's. Je moet er voor zorgen dat de connectie als eerste argument word mee gegeven aan de functies.

2023-12-14 13:38 UTC, AbeLuteijn requested changes
RFC, bekijk mn comments

2023-12-14 13:38 UTC, AbeLuteijn commented on SmartUp/SmartUp.DataAccess.SQLServer/Dao/SemesterRegistrationDao.cs
> +                while (studentCounter < 416)
Maak dit dynamisch, houd altijd rekening met schaalbaarheid

2023-12-14 13:38 UTC, AbeLuteijn commented on SmartUp/SmartUp.DataAccess.SQLServer/Util/TableCreator.cs
> +                PRIMARY KEY(studentId,semesterName)
vergeet de spatie tussen StudentID en SemesterName niet, anders krijg je later errors

2023-12-15 09:47 UTC, AbeLuteijn approved these changes
LGTM!

2023-12-18 09:26 UTC, closed without merging